str.lo: /Users/feilong/data/service/str/ext/str.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/str.c -o str.lo 
kernel/main.lo: /Users/feilong/data/service/str/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/feilong/data/service/str/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/feilong/data/service/str/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /Users/feilong/data/service/str/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/feilong/data/service/str/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/feilong/data/service/str/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/feilong/data/service/str/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /Users/feilong/data/service/str/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/feilong/data/service/str/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /Users/feilong/data/service/str/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/feilong/data/service/str/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/feilong/data/service/str/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /Users/feilong/data/service/str/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /Users/feilong/data/service/str/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/feilong/data/service/str/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/feilong/data/service/str/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/feilong/data/service/str/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /Users/feilong/data/service/str/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /Users/feilong/data/service/str/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/kernel/exit.c -o kernel/exit.lo 
str/camel.lo: /Users/feilong/data/service/str/ext/str/camel.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/str/camel.zep.c -o str/camel.lo 
str/sign.lo: /Users/feilong/data/service/str/ext/str/sign.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/str/sign.zep.c -o str/sign.lo 
str/tools.lo: /Users/feilong/data/service/str/ext/str/tools.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/feilong/data/service/str/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/feilong/data/service/str/ext/str/tools.zep.c -o str/tools.lo 
$(phplibdir)/str.la: ./str.la
	$(LIBTOOL) --mode=install cp ./str.la $(phplibdir)

./str.la: $(shared_objects_str) $(STR_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_str) $(STR_SHARED_LIBADD)

